export async function getSessionHandlerTestSurface() {
  const [
    { sessionAbortHandlers },
    { sessionCompactHandlers },
    { sessionCheckpointHandlers },
    { sessionCheckpointQueryHandlers },
    { sessionCreateHandlers },
    { sessionDeleteHandlers },
    { sessionDispatchHandlers },
    { sessionGroupHandlers },
    { sessionMessagingHandlers },
    { sessionMutationHandlers },
    { sessionReadHandlers },
    { sessionRewindHandlers },
    { sessionSharingHandlers },
    { sessionSubscriptionHandlers },
    { sessionSuggestionHandlers },
  ] = await Promise.all([
    import("../server-methods/sessions-abort.js"),
    import("../server-methods/sessions-compact.js"),
    import("../server-methods/sessions-compaction-checkpoints.js"),
    import("../server-methods/sessions-compaction-queries.js"),
    import("../server-methods/sessions-create.js"),
    import("../server-methods/sessions-delete.js"),
    import("../server-methods/sessions-dispatch.js"),
    import("../server-methods/sessions-groups.js"),
    import("../server-methods/sessions-messaging.js"),
    import("../server-methods/sessions-mutations.js"),
    import("../server-methods/sessions-read.js"),
    import("../server-methods/sessions-rewind.js"),
    import("../server-methods/sessions-sharing.js"),
    import("../server-methods/sessions-subscriptions.js"),
    import("../server-methods/sessions-suggestions.js"),
  ]);
  return {
    ...sessionReadHandlers,
    ...sessionSharingHandlers,
    ...sessionSuggestionHandlers,
    ...sessionSubscriptionHandlers,
    ...sessionCreateHandlers,
    ...sessionCheckpointQueryHandlers,
    ...sessionCheckpointHandlers,
    ...sessionRewindHandlers,
    ...sessionDispatchHandlers,
    ...sessionMessagingHandlers,
    ...sessionAbortHandlers,
    ...sessionMutationHandlers,
    ...sessionDeleteHandlers,
    ...sessionGroupHandlers,
    ...sessionCompactHandlers,
  };
}
