// Slack plugin PoC transport for a credential-owning host bridge.
import { timingSafeEqual } from "node:crypto";
import type { IncomingMessage, ServerResponse } from "node:http";
import type { WebClientOptions } from "@slack/web-api";

export const SLACK_HOST_BRIDGE_SENTINEL_TOKEN = "openclaw-host-bridge";
const SLACK_HOST_BRIDGE_AUTH_HEADER = "x-openclaw-slack-host-authorization";

function isEqualSecret(left: string, right: string): boolean {
  const leftBuffer = Buffer.from(left);
  const rightBuffer = Buffer.from(right);
  return leftBuffer.length === rightBuffer.length && timingSafeEqual(leftBuffer, rightBuffer);
}

function isAuthorizedHostRequest(request: IncomingMessage, authToken: string): boolean {
  const authorization = request.headers.authorization;
  return typeof authorization === "string" && isEqualSecret(authorization, `Bearer ${authToken}`);
}

export function createSlackHostBridgeHttpHandler(params: {
  authToken: string;
  next: (request: IncomingMessage, response: ServerResponse) => Promise<unknown> | unknown;
}) {
  return async (request: IncomingMessage, response: ServerResponse): Promise<void> => {
    if (!isAuthorizedHostRequest(request, params.authToken)) {
      response.statusCode = 401;
      response.end("Unauthorized");
      return;
    }
    await params.next(request, response);
  };
}

export function resolveSlackHostBridgeClientOptions(params: {
  apiUrl: string;
  authToken: string;
}): WebClientOptions {
  return {
    slackApiUrl: params.apiUrl,
    // Host auth proves sandbox identity. It is deliberately separate from the
    // non-secret sentinel Slack authorization generated by WebClient.
    headers: {
      [SLACK_HOST_BRIDGE_AUTH_HEADER]: `Bearer ${params.authToken}`,
    },
    // The credential-owning host must broker every WebClient call. In particular,
    // upload URLs must not silently escape to Slack from the sandbox.
    allowAbsoluteUrls: false,
  };
}
