import {
  SANDBOX_FS_DIRECTORY_MAX_BYTES,
  SANDBOX_FS_DIRECTORY_MAX_ENTRIES,
} from "./fs-bridge.discovery.js";

export const SANDBOX_PINNED_DISCOVERY_PYTHON = [
  `SANDBOX_FS_DIRECTORY_MAX_ENTRIES = ${SANDBOX_FS_DIRECTORY_MAX_ENTRIES}`,
  `SANDBOX_FS_DIRECTORY_MAX_BYTES = ${SANDBOX_FS_DIRECTORY_MAX_BYTES}`,
  "def list_directory(root_fd, rel_path):",
  "    directory_fd = walk_dir(root_fd, rel_path, False)",
  "    try:",
  "        encoded_entries = []",
  "        serialized_bytes = 2",
  "        with os.scandir(directory_fd) as scanner:",
  "            for directory_entry in scanner:",
  "                if len(encoded_entries) >= SANDBOX_FS_DIRECTORY_MAX_ENTRIES:",
  "                    raise OSError(errno.E2BIG, 'directory listing exceeds entry limit', rel_path)",
  "                entry_type = 'directory' if directory_entry.is_dir(follow_symlinks=False) else 'file' if directory_entry.is_file(follow_symlinks=False) else 'other'",
  "                encoded = json.dumps({'name': directory_entry.name, 'type': entry_type}, ensure_ascii=False, separators=(',', ':'))",
  "                serialized_bytes += len(encoded.encode('utf-8')) + (1 if encoded_entries else 0)",
  "                if serialized_bytes > SANDBOX_FS_DIRECTORY_MAX_BYTES:",
  "                    raise OSError(errno.EFBIG, 'directory listing exceeds byte limit', rel_path)",
  "                encoded_entries.append((directory_entry.name, encoded))",
  "        encoded_entries.sort(key=lambda entry: entry[0])",
  "        sys.stdout.write('[' + ','.join(entry[1] for entry in encoded_entries) + ']')",
  "    finally:",
  "        os.close(directory_fd)",
  "",
  "def stat_directory(root_fd, rel_path):",
  "    directory_fd = walk_dir(root_fd, rel_path, False)",
  "    try:",
  "        directory_stat = os.fstat(directory_fd)",
  "        sys.stdout.write('directory|' + str(directory_stat.st_size) + '|' + str(directory_stat.st_mtime))",
  "    finally:",
  "        os.close(directory_fd)",
].join("\n");

export const SANDBOX_PINNED_DISCOVERY_DISPATCH_PYTHON = [
  "elif operation == 'list':",
  "    root_fd = open_dir(sys.argv[2])",
  "    try:",
  "        list_directory(root_fd, sys.argv[3])",
  "    finally:",
  "        os.close(root_fd)",
  "elif operation == 'stat-directory':",
  "    root_fd = open_dir(sys.argv[2])",
  "    try:",
  "        stat_directory(root_fd, sys.argv[3])",
  "    finally:",
  "        os.close(root_fd)",
].join("\n");
