export const MAX_MODEL_TRANSPORT_LOGICAL_CALLS = 64;
export const MAX_MODEL_TRANSPORT_EVENTS = 128;
export const MAX_MODEL_TRANSPORT_ATTEMPTS = 128;
export const MAX_MODEL_TRANSPORT_INVOCATIONS = 128;
