#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

usage() {
  cat <<'EOF'
Usage:
  scripts/dev/computer-use-macos-live-rig.sh prepare <profile> <port> <app> <scratch> [peekaboo|cua]
  scripts/dev/computer-use-macos-live-rig.sh gateway <scratch>
  scripts/dev/computer-use-macos-live-rig.sh app <scratch> [peekaboo|cua]
  scripts/dev/computer-use-macos-live-rig.sh nodes <scratch>
  scripts/dev/computer-use-macos-live-rig.sh proof <scratch> <window-title> <text> [element-label]

The rig is maintainer-only and loopback-only. Run gateway and app in separate
terminals, approve the dedicated CLI device after its first `nodes` request,
then run `proof`. Never use the operator profile or port 18789.
EOF
}

fail() {
  echo "computer-use live rig: $*" >&2
  exit 1
}

validate_provider() {
  case "$1" in
    peekaboo | cua) ;;
    *) fail "provider must be peekaboo or cua" ;;
  esac
}

load_rig() {
  local scratch="$1"
  [[ "$scratch" = /* ]] || fail "scratch path must be absolute"
  [[ -f "$scratch/rig.env" ]] || fail "missing $scratch/rig.env; run prepare first"
  # Generated by prepare from validated scalar values and shell-escaped paths.
  # shellcheck disable=SC1090
  source "$scratch/rig.env"
  [[ "${OPENCLAW_CU_RIG_ROOT:-}" == "$repo_root" ]] ||
    fail "rig belongs to a different checkout: ${OPENCLAW_CU_RIG_ROOT:-unknown}"
}

prepare() {
  [[ $# -ge 4 && $# -le 5 ]] || { usage; exit 2; }
  local profile="$1"
  local port="$2"
  local app_input="$3"
  local scratch="$4"
  local provider="${5:-peekaboo}"

  [[ "$profile" =~ ^[A-Za-z0-9][A-Za-z0-9_-]+$ ]] ||
    fail "profile must contain only letters, digits, underscores, and dashes"
  case "$profile" in
    default | main | local) fail "choose a fresh, explicitly isolated profile" ;;
  esac
  [[ "$port" =~ ^[0-9]+$ ]] || fail "port must be numeric"
  ((port >= 1024 && port <= 65535)) || fail "port must be between 1024 and 65535"
  ((port != 18789)) || fail "port 18789 belongs to the operator gateway"
  [[ "$scratch" = /* ]] || fail "scratch path must be absolute"
  validate_provider "$provider"

  local app_path
  app_path="$(cd "$(dirname "$app_input")" && pwd)/$(basename "$app_input")"
  local app_executable="$app_path/Contents/MacOS/OpenClaw"
  [[ -x "$app_executable" ]] || fail "signed app executable not found: $app_executable"
  codesign --verify --deep --strict "$app_path" >/dev/null 2>&1 ||
    fail "app is not a valid signed bundle: $app_path"

  git -C "$repo_root" diff --quiet -- src packages extensions scripts/run-node.mjs scripts/run-node.mts ||
    fail "runtime sources are dirty; commit and rebuild before launching the node worker"
  git -C "$repo_root" diff --cached --quiet -- src packages extensions scripts/run-node.mjs scripts/run-node.mts ||
    fail "runtime sources are staged but uncommitted; commit and rebuild first"

  [[ ! -e "$scratch/rig.env" ]] || fail "$scratch already contains a rig"
  mkdir -p "$scratch" "$scratch/agent-state"

  local app_state="$HOME/.openclaw-$profile"
  local app_config="$app_state/openclaw.json"
  local staged_app_config="$scratch/app.json"
  local gateway_config="$scratch/gateway.json"

  node - "$port" >"$gateway_config" <<'NODE'
const port = Number(process.argv[2]);
process.stdout.write(`${JSON.stringify({
  gateway: {
    mode: "local",
    port,
    auth: { mode: "none" },
    nodes: { commands: { allow: ["computer.act"] } },
  },
}, null, 2)}\n`);
NODE

  node - "$port" >"$staged_app_config" <<'NODE'
const port = Number(process.argv[2]);
process.stdout.write(`${JSON.stringify({
  gateway: {
    mode: "remote",
    port,
    auth: { mode: "none" },
    nodes: { commands: { allow: ["computer.act"] } },
    remote: { transport: "direct", url: `ws://127.0.0.1:${port}` },
  },
}, null, 2)}\n`);
NODE

  mkdir -p "$app_state"
  if [[ -e "$app_config" ]] && ! cmp -s "$staged_app_config" "$app_config"; then
    fail "$app_config already exists with different contents; choose a fresh profile"
  fi
  cp "$staged_app_config" "$app_config"
  chmod 600 "$app_config" "$gateway_config"

  local defaults_domain="ai.openclaw.mac.profile.$profile"
  defaults write "$defaults_domain" openclaw.macNodeIdentityProfile -string node
  defaults write "$defaults_domain" openclaw.connectionMode -string remote
  defaults write "$defaults_domain" openclaw.pauseEnabled -bool false
  defaults write "$defaults_domain" openclaw.computerControlEnabled -bool true
  defaults write "$defaults_domain" openclaw.computerControlProvider -string "$provider"
  defaults write "$defaults_domain" openclaw.gatewayProjectRootPath -string "$repo_root"
  defaults write "$defaults_domain" openclaw.onboardingSeen -bool true
  defaults write "$defaults_domain" openclaw.onboardingVersion -int 8

  {
    printf 'OPENCLAW_CU_RIG_ROOT=%q\n' "$repo_root"
    printf 'OPENCLAW_CU_RIG_PROFILE=%q\n' "$profile"
    printf 'OPENCLAW_CU_RIG_PORT=%q\n' "$port"
    printf 'OPENCLAW_CU_RIG_APP=%q\n' "$app_path"
    printf 'OPENCLAW_CU_RIG_APP_STATE=%q\n' "$app_state"
    printf 'OPENCLAW_CU_RIG_GATEWAY_CONFIG=%q\n' "$gateway_config"
    printf 'OPENCLAW_CU_RIG_AGENT_STATE=%q\n' "$scratch/agent-state"
  } >"$scratch/rig.env"
  chmod 600 "$scratch/rig.env"

  echo "prepared isolated profile $profile on ws://127.0.0.1:$port"
  echo "gateway: $0 gateway $scratch"
  echo "app:     $0 app $scratch $provider"
  echo "nodes:   $0 nodes $scratch"
}

run_gateway() {
  [[ $# -eq 1 ]] || { usage; exit 2; }
  load_rig "$1"
  exec env \
    OPENCLAW_CONFIG_PATH="$OPENCLAW_CU_RIG_GATEWAY_CONFIG" \
    OPENCLAW_STATE_DIR="$OPENCLAW_CU_RIG_APP_STATE" \
    node "$repo_root/scripts/run-node.mjs" --profile "$OPENCLAW_CU_RIG_PROFILE" \
      gateway run --port "$OPENCLAW_CU_RIG_PORT" --auth none --force --verbose
}

run_app() {
  [[ $# -ge 1 && $# -le 2 ]] || { usage; exit 2; }
  load_rig "$1"
  local provider="${2:-peekaboo}"
  validate_provider "$provider"
  defaults write "ai.openclaw.mac.profile.$OPENCLAW_CU_RIG_PROFILE" \
    openclaw.computerControlProvider -string "$provider"
  exec env OPENCLAW_PROFILE="$OPENCLAW_CU_RIG_PROFILE" \
    "$OPENCLAW_CU_RIG_APP/Contents/MacOS/OpenClaw"
}

run_nodes() {
  [[ $# -eq 1 ]] || { usage; exit 2; }
  load_rig "$1"
  exec env \
    OPENCLAW_CONFIG_PATH="$OPENCLAW_CU_RIG_GATEWAY_CONFIG" \
    OPENCLAW_STATE_DIR="$OPENCLAW_CU_RIG_AGENT_STATE" \
    node "$repo_root/scripts/run-node.mjs" nodes list --json
}

run_proof() {
  [[ $# -ge 3 && $# -le 4 ]] || { usage; exit 2; }
  local scratch="$1"
  load_rig "$scratch"
  local args=(
    --window-title "$2"
    --text "$3"
    --artifacts "$scratch"
  )
  if [[ $# -eq 4 ]]; then
    args+=(--element-label "$4")
  fi
  exec env \
    OPENCLAW_CONFIG_PATH="$OPENCLAW_CU_RIG_GATEWAY_CONFIG" \
    OPENCLAW_STATE_DIR="$OPENCLAW_CU_RIG_AGENT_STATE" \
    node --import tsx "$repo_root/scripts/dev/computer-use-macos-live-proof.ts" "${args[@]}"
}

command_name="${1:-}"
[[ -n "$command_name" ]] || { usage; exit 2; }
shift
case "$command_name" in
  prepare) prepare "$@" ;;
  gateway) run_gateway "$@" ;;
  app) run_app "$@" ;;
  nodes) run_nodes "$@" ;;
  proof) run_proof "$@" ;;
  -h | --help | help) usage ;;
  *) usage; exit 2 ;;
esac
