// Public diagnostic event types omit core-only events and inputs.
import type {
  DiagnosticEventInput as AllDiagnosticEventInput,
  DiagnosticEventPayload as AllDiagnosticEventPayload,
  DiagnosticSessionMaintenancePrunedEvent,
} from "../infra/diagnostic-events.js";

export type {
  DiagnosticAsyncQueueDroppedEvent,
  DiagnosticContextAssembledEvent,
  DiagnosticEventMetadata,
  DiagnosticEventPrivateData,
  DiagnosticExecApprovalFollowupSuppressedEvent,
  DiagnosticExecProcessCompletedEvent,
  DiagnosticFailoverEvent,
  DiagnosticHeartbeatEvent,
  DiagnosticHarnessRunCompletedEvent,
  DiagnosticHarnessRunErrorEvent,
  DiagnosticHarnessRunOutcome,
  DiagnosticHarnessRunPhase,
  DiagnosticHarnessRunStartedEvent,
  DiagnosticLaneDequeueEvent,
  DiagnosticLaneEnqueueEvent,
  DiagnosticLivenessWarningEvent,
  DiagnosticLivenessWarningReason,
  DiagnosticLogRecordEvent,
  DiagnosticMemoryPressureEvent,
  DiagnosticMemorySampleEvent,
  DiagnosticMemoryUsage,
  DiagnosticMessageDeliveryCompletedEvent,
  DiagnosticMessageDeliveryErrorEvent,
  DiagnosticMessageDeliveryKind,
  DiagnosticMessageDeliveryStartedEvent,
  DiagnosticMessageDispatchCompletedEvent,
  DiagnosticMessageDispatchStartedEvent,
  DiagnosticMessageProcessedEvent,
  DiagnosticMessageQueuedEvent,
  DiagnosticMessageReceivedEvent,
  DiagnosticModelCallCompletedEvent,
  DiagnosticModelCallErrorEvent,
  DiagnosticModelCallStartedEvent,
  DiagnosticModelCallContent,
  DiagnosticPayloadLargeEvent,
  DiagnosticPhaseCompletedEvent,
  DiagnosticPhaseDetails,
  DiagnosticPhaseSnapshot,
  DiagnosticRunAttemptEvent,
  DiagnosticRunCompletedEvent,
  DiagnosticRunProgressEvent,
  DiagnosticRunStartedEvent,
  DiagnosticSecurityEvent,
  DiagnosticSecurityEventActor,
  DiagnosticSecurityEventControl,
  DiagnosticSecurityEventInput,
  DiagnosticSecurityEventPolicy,
  DiagnosticSecurityEventTarget,
  DiagnosticSessionActiveWorkKind,
  DiagnosticSessionAttentionClassification,
  DiagnosticSessionLongRunningEvent,
  DiagnosticSessionRecoveryCompletedEvent,
  DiagnosticSessionRecoveryRequestedEvent,
  DiagnosticSessionRecoveryStatus,
  DiagnosticSessionStalledEvent,
  DiagnosticSessionState,
  DiagnosticSessionStateEvent,
  DiagnosticSessionStuckEvent,
  DiagnosticSessionTurnCreatedEvent,
  DiagnosticSkillActivation,
  DiagnosticSkillTelemetrySource,
  DiagnosticSkillUsedEvent,
  DiagnosticSkillUsagePrivateData,
  DiagnosticTalkEvent,
  DiagnosticTelemetryExporterEvent,
  DiagnosticToolExecutionBlockedEvent,
  DiagnosticToolExecutionCompletedEvent,
  DiagnosticToolExecutionErrorEvent,
  DiagnosticToolExecutionStartedEvent,
  DiagnosticToolCallContent,
  DiagnosticToolLoopEvent,
  DiagnosticToolParamsSummary,
  DiagnosticToolSource,
  DiagnosticToolTerminalReason,
  DiagnosticUsageEvent,
  DiagnosticWebhookErrorEvent,
  DiagnosticWebhookProcessedEvent,
  DiagnosticWebhookReceivedEvent,
  TrustedToolExecutionEvent,
} from "../infra/diagnostic-events.js";

type InternalDiagnosticEvent = Extract<
  AllDiagnosticEventPayload,
  { type: "session.maintenance.pruned" }
>;

export type DiagnosticEventPayload = Exclude<AllDiagnosticEventPayload, InternalDiagnosticEvent>;
export type DiagnosticEventInput = Exclude<
  AllDiagnosticEventInput,
  Omit<InternalDiagnosticEvent, "seq" | "ts">
>;
